export /home/huy/FabricNetwork/OrgOrderer/bin:$PATH
  echo Enrolling the CA admin
  mkdir -p /home/huy/FabricNetwork/OrgOrd/example.com

  export FABRIC_CA_CLIENT_HOME=/home/huy/FabricNetwork/OrgOrd/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-orderer --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p /home/huy/FabricNetwork/OrgOrd/example.com/msp/tlscacerts
  cp /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem /home/huy/FabricNetwork/OrgOrd/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p /home/huy/FabricNetwork/OrgOrd/example.com/tlsca
  cp /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem /home/huy/FabricNetwork/OrgOrd/example.com/tlsca/tlsca.example.com-cert.pem

  echo Registering orderer1
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer1 --id.secret orderer1pw --id.type orderer --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  echo Registering orderer2
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer2 --id.secret orderer2pw --id.type orderer --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  echo Registering orderer3
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer3 --id.secret orderer3pw --id.type orderer --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null


  echo Registering the orderer admin
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  echo "Registering peer0"
  set -x
fabric-ca-client register --caname ca-orderer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

echo "Registering peer1"
  set -x
fabric-ca-client register --caname ca-orderer --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null


  echo Generating the orderer1 msp
  set -x
  fabric-ca-client enroll -u https://orderer1:orderer1pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/msp --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  cp /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/msp/config.yaml

  echo Generating the orderer2 msp
  set -x
  fabric-ca-client enroll -u https://orderer2:orderer2pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/msp --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  cp /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/msp/config.yaml

  echo Generating the orderer3 msp
  set -x
  fabric-ca-client enroll -u https://orderer3:orderer3pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/msp --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  cp /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/msp/config.yaml

   echo "Generating the peer0 msp"
  set -x
fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/msp --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem  
{ set +x; } 2>/dev/null

  cp /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/msp/config.yaml

 echo "Generating the peer1 msp"
  set -x
fabric-ca-client enroll -u https://peer1:peer1pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/msp --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem  
{ set +x; } 2>/dev/null

cp /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/msp/config.yaml


  echo Generating the orderer1-tls certificates, use --csr.hosts to specify Subject Alternative Names
  set -x
  fabric-ca-client enroll -u https://orderer1:orderer1pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls --enrollment.profile tls --csr.hosts orderer1.example.com --csr.hosts localhost --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/ca.crt
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/signcerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/server.crt
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/keystore/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/server.key

  echo Generating the orderer2-tls certificates, use --csr.hosts to specify Subject Alternative Names
  set -x
  fabric-ca-client enroll -u https://orderer2:orderer2pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls --enrollment.profile tls --csr.hosts orderer2.example.com --csr.hosts localhost --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/ca.crt
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/signcerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/server.crt
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/keystore/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/server.key

  echo Generating the orderer3-tls certificates, use --csr.hosts to specify Subject Alternative Names
  set -x
  fabric-ca-client enroll -u https://orderer3:orderer3pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls --enrollment.profile tls --csr.hosts orderer3.example.com --csr.hosts localhost --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/ca.crt
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/signcerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/server.crt
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/keystore/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/server.key

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls --enrollment.profile tls --csr.hosts peer0.orgOrd.example.com --csr.hosts localhost --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem 
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls/ca.crt
cp /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls/signcerts/* /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls/server.crt
cp /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls/keystore/* /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer0.orgOrd.example.com/tls/server.key

echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
fabric-ca-client enroll -u https://peer1:peer1pw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls --enrollment.profile tls --csr.hosts peer1.orgOrd.example.com --csr.hosts localhost --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem 
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls/ca.crt
cp /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls/signcerts/* /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls/server.crt
cp /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls/keystore/* /home/huy/FabricNetwork/OrgOrd/example.com/peers/peer1.orgOrd.example.com/tls/server.key

  # Copy orderer org's CA cert to orderer1's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/msp/tlscacerts
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

   # Copy orderer org's CA cert to orderer2's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/msp/tlscacerts
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

   # Copy orderer org's CA cert to orderer3's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/msp/tlscacerts
  cp /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/tls/tlscacerts/* /home/huy/FabricNetwork/OrgOrd/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

  echo Generating the admin msp
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:11054 --caname ca-orderer -M /home/huy/FabricNetwork/OrgOrd/example.com/users/Admin@example.com/msp --tls.certfiles /home/huy/FabricNetwork/OrgOrd/runCA/ca-cert.pem
  { set +x; } 2>/dev/null

  cp /home/huy/FabricNetwork/OrgOrd/example.com/msp/config.yaml /home/huy/FabricNetwork/OrgOrd/example.com/users/Admin@example.com/msp/config.yaml

 
  


